version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: 'zookeeper'
    networks:
      - my-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 
  kafka:
    image: 'wurstmeister/kafka'
    container_name: 'kafka'
    networks:
      - my-network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      
networks:
  my-network:
 
